---
- name: Instalar impressora Central Piso 2
  hosts: all
  gather_facts: no

  tasks:

    - name: Adicionar impressora
      ansible.windows.win_shell: |
        Start-Process rundll32.exe -ArgumentList 'printui.dll,PrintUIEntry /in /n "\\192.168.15.131\Central Piso 2"'

    - name: Verificar impressoras instaladas
      ansible.windows.win_shell: |
        Get-Printer | Select-Object Name
      register: impressoras

    - name: Mostrar impressoras
      debug:
        var: impressoras.stdout_lines
