---
- name: Testar acesso impressora
  hosts: all
  gather_facts: no

  tasks:

    - name: Ver impressoras do servidor
      ansible.windows.win_shell: |
        Get-Printer -ComputerName 192.168.15.131 | Select Name,ShareName
      register: impressoras

    - name: Mostrar
      debug:
        var: impressoras.stdout_lines
